sudo: false
dist: trusty

language: cpp
compiler:
  - clang

git:
  depth: 1

addons:
  apt:
    packages:
      - libboost1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-iostreams1.55-dev
      - libboost-program-options1.55-dev
      - libboost-regex1.55-dev
      - libboost-system1.55-dev
      - libboost-thread1.55-dev
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev
      - libace-dev
      - libncurses5-dev
      - build-essential
      - autoconf
      - libtool
      - make
      - cmake
      - git-core
      - patch
      - wget
      - links
      - zip
      - unzip
      - unrar

services:
  - mysql

before_install:
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init
  
script:
  - mkdir build
  - cd build
  - cmake ../ -DSCRIPTS=0 -DTOOLS=1
  - make -j8

notifications:
  irc:
    channels:
      - "irc.rizon.net#project_skyfire"
    on_success: always
    on_failure: always
